### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by axiomofjoy** [conda-forge/apsw-feedstock#48]
### Comment:

I am interested in incorporating `apsw` into an open-source project. We distribute our package via Conda, so our dependencies must also be supported on Conda. It looks like it's been a while since the last release of this feedstock. I'm curious if there any hurdles to bringing back Conda support for the latest versions of `apsw`?

**Comment by stuertz** [comment]
Mostly lack of time. Maybe you can jump in?

I will have a quick look on the pending MRs

**Comment by axiomofjoy** [comment]
Thanks for the quick reply! Let me circle back with the team and get back to you.

**Comment by stuertz** [comment]
With #51 this has been updated to 3.45.1

**Comment by axiomofjoy** [comment]
Thank you!
