### ISSUE TITLE
`osx-arm64` migration

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/apsw-feedstock#57]
### Comment:

This feedstock doesn't have M1/Apple Silicon/`osx-arm64` builds, which appear to be supported upstream.

I don't have time to do this myself next week, but if anybody wishes to snipe me: https://conda-forge.org/blog/2020/10/29/macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock

**Comment by loriab** [comment]
started that https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6200
